# CI/CD: Runs evals on Pull Request
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: poetry
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install deps
        run: poetry install --no-interaction --with dev --no-root
      - name: Run tests
        run: poetry run pytest
